version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 1234:1234
    volumes:
      - "./frontend/app/node_modules:/app/node_modules"
      - "./frontend/app/src:/app/src"
    environment:
      API_BASE_URL: http://localhost:5001/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://db_user:db_password@db:5432/doctors_db
    ports:
      - 5001:5000
    volumes:
      - "./backend/app:/app"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - onlinedoctor-database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: doctors_db

volumes:
  onlinedoctor-database-data: