version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "lts/*"
    environment:
      DATABASE_URL: postgresql+psycopg2://db_user:db_password@db:5432/doctors_db
      PYTHONPATH: /workspace/backend/app
      API_BASE_URL: http://localhost:5000/
    volumes:
      - ..:/workspace:cached  
    command: sleep infinity
    network_mode: service:db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: doctors_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
